# Generated by Django 3.1.7 on 2021-05-14 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('published', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['published'],
            },
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gadgets/')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.PositiveSmallIntegerField(choices=[(0, 'Аксуский'), (1, 'Алаколь'), (2, 'Балхаш'), (3, 'Енбекшиказах'), (4, 'Ескельдинский'), (5, 'Жамбылский'), (6, 'Илийский'), (7, 'Карасайский'), (8, 'Каратальский'), (9, 'Кегенский'), (10, 'Кербульский'), (11, 'Коксуский'), (12, 'Панфиловский'), (13, 'Райымбекский'), (14, 'Сарканский'), (15, 'Талгарский'), (16, 'Уйгурский'), (17, 'Талдыкорган'), (18, 'Капшагай'), (19, 'Текели')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('region_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.region')),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'DeliveryAddress',
                'verbose_name_plural': 'DeliveryAddresses',
            },
            bases=('api.region',),
        ),
    ]
